---
# A better diff tool
# https://github.com/dandavison/delta
- name: Install delta
  apt:
    state: present
    deb: https://github.com/dandavison/delta/releases/download/0.10.3/git-delta_0.10.3_amd64.deb

# update .gitconfig? 
