---
# Install kubectl
- name: k8s deps
  apt:
    update_cache: true
    state: present
    pkg:
      - gnupg
      - apt-transport-https
      - ca-certificates
- name: Add Google apt key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/k8s-apt-google.gpg
    state: present
- name: Add kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/k8s-apt-google.gpg] https://apt.kubernetes.io/ {{ ansible_distribution_release }} main
    state: present
- name: Install kubectl
  apt:
    update_cache: true
    state: present
    pkg: kubectl
