---
# https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html#cliv2-linux-install
- name: Install the awscli 
  hosts: localhost
  become: true
  tasks:
    - name: Download
      ansible.builtin.unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/
        remote_src: true
    - name: Install
      become: true
      command:
        cmd: /tmp/aws/install
