---
 # Install EdgeDelta and configure journald -> rsyslog -> edgedelta
- hosts: localhost
  become: true
  tasks:
    - name: Get EdgeDelta Agent
      get_url:
        url: https://release.edgedelta.com/release/install.sh 
        dest: /tmp/install.sh
        mode: "0744"
    - name: Install EdgeDelta agent
      shell:
        cmd: "ED_API_KEY={{ ed_api_key }} /tmp/install.sh"
        creates: /etc/systemd/system/edgedelta.service
    - name: Updated journald conf for syslog forwarding
      ini_file:
        path: /etc/systemd/journald.conf
        section: Journal
        option: ForwardToSyslog
        value: true
    - name: Restart journald for config change
      systemd:
        name: systemd-journald.service
        state: restarted
    - name: Update rsyslog conf
      lineinfile:
        create: true
        path: /etc/rsyslog.d/60-edgedelta.conf
        line: "*.* @@127.0.0.1:514"
    - name: Restart rsyslog
      systemd:
        name: syslog.service
        state: restarted
        enabled: true
