#!/bin/bash
#
# helper script for local development testing against a docker container

DOCKERFILE_WORKDIR="/opt/app"
CONTAINER="<long_registy_url>/<image_name>:<long_tag_name>"

docker run --rm -it --entrypoint="" \
    -e AWS_SECRET_ACCESS_KEY \
    -e AWS_ACCESS_KEY_ID \
    -e AWS_SESSION_TOKEN \
    -v $PWD:"$DOCKERFILE_WORKDIR" \
    "$CONTAINER" \
    /bin/bash
