#!/bin/bash

AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
AWS_REGION=$(aws configure get region --output text)
AWS_ECR_USERNAME="AWS"

echo "Login url:" "${AWS_ACCOUNT_ID}".dkr.ecr."${AWS_REGION}".amazonaws.com

aws ecr get-login-password --region "${AWS_REGION}" --output text | docker login --username "${AWS_ECR_USERNAME}" --password-stdin "${AWS_ACCOUNT_ID}".dkr.ecr."${AWS_REGION}".amazonaws.com
